# Generated by Django 5.1.1 on 2024-09-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, default=True, max_length=255, null=True),
        ),
    ]
