# Generated by Django 5.1.1 on 2024-10-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.user.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
